from django.urls import path
from django.conf import settings
from django.conf.urls.static import static
from . import views
from .auth import EmailOrUsernameTokenObtainPairView
from .views import (
    send_institutional_otp,
    verify_institutional_otp,
    confirm_cv_items,
    paper_search_external,
    bulk_publish_papers,
    extract_abstract_from_pdf,
    generate_paper_keywords,
    generate_faculty_bio,
    generate_research_interests,
    generate_faculty_keywords,
    admin_me,
    approve_faculty_suggestion,
    FacultyListCreateView,
    FacultyDetailView,
    faculty_me,
    faculty_me_suggestions,
    faculty_suggestion_preview,
    network_discovery,
    public_search_data,
    semantic_paper_search,
    reject_faculty_suggestion,
    PaperListCreateView,
    PaperDetailView,
    ProjectListCreateView,
    ProjectDetailView,
    PatentListCreateView,
    PatentDetailView,
    FacultyPhotoUploadView,
    FacultyUploadCVPapers,
    contact_team_list,
    admin_contact_team_list,
    admin_contact_team_detail,
    contact_settings,
    admin_contact_settings,
    admin_contact_team_photo_upload,
    # Admin management endpoints
    AdminSchoolListCreateView,
    AdminSchoolDetailView,
    AdminDepartmentListCreateView,
    AdminDepartmentDetailView,
    admin_faculty_list,
    admin_faculty_detail,
    admin_approve_faculty,
    admin_reject_faculty,
    admin_paper_list,
    admin_paper_detail,
    admin_project_detail,
    admin_patent_detail,
    unified_search,
)
from rest_framework_simplejwt.views import (
    TokenRefreshView,
)
urlpatterns = [
    path('', views.home, name='home'),
    path("search/", unified_search, name="unified-search"),
    path("public/search-data/", public_search_data, name="public-search-data"),
    path("network/discovery/", network_discovery, name="network-discovery"),
    path("semantic/papers/", semantic_paper_search, name="semantic-paper-search"),

    path('faculty/', FacultyListCreateView.as_view(), name='faculty-list'),
    path('faculty/<int:pk>/', FacultyDetailView.as_view(), name='faculty-detail'),
    path('faculty/me/', faculty_me, name='faculty_me'),
    path('admin/me/', admin_me, name='admin_me'),
    path("faculty/me/suggestions/", faculty_me_suggestions, name="faculty-me-suggestions"),
    path(
        "faculty/me/suggestions/<int:external_faculty_id>/approve/",
        approve_faculty_suggestion,
        name="faculty-suggestion-approve",
    ),
    path(
        "faculty/me/suggestions/<int:external_faculty_id>/preview/",
        faculty_suggestion_preview,
        name="faculty-suggestion-preview",
    ),
    path(
        "faculty/me/suggestions/<int:external_faculty_id>/reject/",
        reject_faculty_suggestion,
        name="faculty-suggestion-reject",
    ),
    path("papers/", PaperListCreateView.as_view(), name="paper-list"),
    path("papers/<int:pk>/", PaperDetailView.as_view(), name="paper-detail"),
    path("projects/", ProjectListCreateView.as_view(), name="project-list"),
    path("projects/<int:pk>/", ProjectDetailView.as_view(), name="project-detail"),
    path("patents/", PatentListCreateView.as_view(), name="patent-list"),
    path("patents/<int:pk>/", PatentDetailView.as_view(), name="patent-detail"),
    path("faculty/signup/", views.faculty_signup, name="faculty_signup"),
    path("token/", EmailOrUsernameTokenObtainPairView.as_view(), name="token_obtain_pair"),
    path("token/refresh/", TokenRefreshView.as_view(), name="token_refresh"),
    path("auth/forgot-password/", views.forgot_password, name="forgot-password"),
    path("auth/reset-password/", views.reset_password, name="reset-password"),
    path("auth/send-otp/", send_institutional_otp, name="send-otp"),
    path("auth/verify-otp/", verify_institutional_otp, name="verify-otp"),
    path("faculty/upload-photo/", FacultyPhotoUploadView.as_view()),
    path("faculty/upload-cv-papers/", FacultyUploadCVPapers.as_view(), name="upload-cv-papers"),
    path("faculty/confirm-cv-items/", confirm_cv_items, name="confirm-cv-items"),
    path("faculty/paper-search/", paper_search_external, name="paper-search-external"),
    path("faculty/papers/bulk-publish/", bulk_publish_papers, name="bulk-publish-papers"),
    path("faculty/extract-abstract/", extract_abstract_from_pdf, name="extract-abstract"),
    path("faculty/generate-keywords/", generate_paper_keywords, name="generate-keywords"),
    path("faculty/generate-bio/", generate_faculty_bio, name="generate-bio"),
    path("faculty/generate-research-interests/", generate_research_interests, name="generate-research-interests"),
    path("faculty/generate-profile-keywords/", generate_faculty_keywords, name="generate-profile-keywords"),
    path("contact/team/", contact_team_list, name="contact-team-list"),
    path("contact/settings/", contact_settings, name="contact-settings"),
    path("admin/contact/team/", admin_contact_team_list, name="admin-contact-team-list"),
    path("admin/contact/team/<int:pk>/", admin_contact_team_detail, name="admin-contact-team-detail"),
    path("admin/contact/settings/", admin_contact_settings, name="admin-contact-settings"),
    path("admin/contact/team/<int:pk>/photo/", admin_contact_team_photo_upload, name="admin-contact-team-photo"),

    # Schools & Departments
    path("admin/schools/", AdminSchoolListCreateView.as_view(), name="admin-school-list"),
    path("admin/schools/<int:pk>/", AdminSchoolDetailView.as_view(), name="admin-school-detail"),
    path("admin/departments/", AdminDepartmentListCreateView.as_view(), name="admin-department-list"),
    path("admin/departments/<int:pk>/", AdminDepartmentDetailView.as_view(), name="admin-department-detail"),

    # Faculty admin
    path("admin/faculty/", admin_faculty_list, name="admin-faculty-list"),
    path("admin/faculty/<int:pk>/", admin_faculty_detail, name="admin-faculty-detail"),
    path("admin/faculty/<int:pk>/approve/", admin_approve_faculty, name="admin-faculty-approve"),
    path("admin/faculty/<int:pk>/reject/", admin_reject_faculty, name="admin-faculty-reject"),

    # Papers, Projects, Patents admin
    path("admin/papers/", admin_paper_list, name="admin-paper-list"),
    path("admin/papers/<int:pk>/", admin_paper_detail, name="admin-paper-detail"),
    path("admin/projects/<int:pk>/", admin_project_detail, name="admin-project-detail"),
    path("admin/patents/<int:pk>/", admin_patent_detail, name="admin-patent-detail"),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
