# Generated by Django 5.2.7 on 2026-04-25 14:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('general_email', models.EmailField(blank=True, max_length=254)),
                ('support_email', models.EmailField(blank=True, max_length=254)),
                ('github_url', models.URLField(blank=True)),
                ('linkedin_url', models.URLField(blank=True)),
                ('address_line_1', models.CharField(blank=True, max_length=200)),
                ('address_line_2', models.CharField(blank=True, max_length=200)),
                ('address_line_3', models.CharField(blank=True, max_length=200)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='ContactTeamMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('role', models.CharField(max_length=200)),
                ('description', models.TextField(blank=True)),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('linkedin_url', models.URLField(blank=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='contact_photos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('is_visible', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('code', models.CharField(blank=True, max_length=32, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['school__display_order', 'school__name', 'name'],
            },
        ),
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('code', models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('display_order', models.PositiveIntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['display_order', 'name'],
            },
        ),
        migrations.CreateModel(
            name='Faculty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('faculty_id', models.CharField(max_length=100, unique=True)),
                ('first_name', models.CharField(blank=True, max_length=100, null=True)),
                ('last_name', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=255, null=True)),
                ('department', models.CharField(blank=True, max_length=255, null=True)),
                ('email', models.EmailField(blank=True, max_length=254, null=True, unique=True)),
                ('office', models.CharField(blank=True, max_length=255, null=True)),
                ('room', models.CharField(blank=True, max_length=100, null=True)),
                ('phone', models.CharField(blank=True, max_length=20, null=True)),
                ('bio', models.TextField(blank=True, null=True)),
                ('faculty_keywords', models.TextField(blank=True, null=True)),
                ('ai_keywords', models.TextField(blank=True, null=True)),
                ('profile_visibility', models.BooleanField(default=True)),
                ('is_approved', models.BooleanField(default=False)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='faculty_photos/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(blank=True, max_length=255, null=True)),
                ('total_citations', models.IntegerField(default=0)),
                ('article_count', models.IntegerField(default=0)),
                ('average_citations', models.FloatField(default=0.0)),
                ('review_status', models.CharField(choices=[('pending', 'Pending Review'), ('confirmed_su', 'Confirmed SU Faculty'), ('external', 'External Collaborator'), ('archived', 'Archived'), ('rejected', 'Rejected')], db_index=True, default='pending', max_length=24)),
                ('confirmed_su_faculty', models.BooleanField(db_index=True, default=False)),
                ('cleanup_notes', models.TextField(blank=True, null=True)),
                ('school', models.CharField(blank=True, max_length=255, null=True)),
                ('school_affiliations', models.JSONField(blank=True, default=list)),
                ('department_affiliations', models.JSONField(blank=True, default=list)),
                ('dois', models.JSONField(blank=True, default=list)),
                ('titles', models.JSONField(blank=True, default=list)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('journals', models.JSONField(blank=True, default=list)),
                ('departments', models.ManyToManyField(blank=True, related_name='faculty', to='academic.department')),
                ('primary_department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_faculty', to='academic.department')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='faculty_profile', to=settings.AUTH_USER_MODEL)),
                ('primary_school', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='primary_faculty', to='academic.school')),
                ('schools', models.ManyToManyField(blank=True, related_name='faculty', to='academic.school')),
            ],
        ),
        migrations.CreateModel(
            name='Paper',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('doi', models.CharField(max_length=255, unique=True)),
                ('title', models.CharField(max_length=500)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('journal', models.CharField(blank=True, max_length=255, null=True)),
                ('date_published', models.DateField(blank=True, null=True)),
                ('download_url', models.URLField(blank=True, null=True)),
                ('license_url', models.URLField(blank=True, null=True)),
                ('ai_keywords', models.JSONField(blank=True, null=True)),
                ('faculty_keywords', models.JSONField(blank=True, null=True)),
                ('tc_count', models.IntegerField(default=0)),
                ('date_published_online', models.DateField(blank=True, null=True)),
                ('date_published_print', models.DateField(blank=True, null=True)),
                ('url', models.URLField(blank=True, null=True)),
                ('keywords', models.JSONField(blank=True, default=list)),
                ('themes', models.JSONField(blank=True, default=list)),
                ('faculty_members', models.JSONField(blank=True, default=list)),
                ('faculty_affiliations', models.JSONField(blank=True, default=dict)),
                ('engagement_metrics', models.JSONField(blank=True, default=dict)),
                ('paper_embedding', models.JSONField(blank=True, default=list)),
                ('embedding_model', models.CharField(blank=True, default='', max_length=64)),
                ('embedding_updated_at', models.DateTimeField(blank=True, null=True)),
                ('authors', models.ManyToManyField(blank=True, related_name='papers', to='academic.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Patent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('abstract', models.TextField(blank=True, null=True)),
                ('patent_number', models.CharField(max_length=100, unique=True)),
                ('filing_date', models.DateField(blank=True, null=True)),
                ('issue_date', models.DateField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('aiKeywords', models.JSONField(blank=True, null=True)),
                ('faculty', models.ManyToManyField(blank=True, related_name='patents', to='academic.faculty')),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField(blank=True, null=True)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('funding_source', models.CharField(blank=True, max_length=200, null=True)),
                ('status', models.CharField(blank=True, max_length=100, null=True)),
                ('keywords', models.JSONField(blank=True, null=True)),
                ('link', models.URLField(blank=True, null=True)),
                ('faculty', models.ManyToManyField(blank=True, related_name='projects', to='academic.faculty')),
            ],
        ),
        migrations.AddField(
            model_name='department',
            name='school',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='departments', to='academic.school'),
        ),
        migrations.CreateModel(
            name='FacultySuggestionDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decision', models.CharField(choices=[('approved', 'Approved'), ('rejected', 'Rejected')], max_length=16)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('external_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_by', to='academic.faculty')),
                ('reviewer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestion_decisions', to='academic.faculty')),
            ],
            options={
                'unique_together': {('reviewer', 'external_faculty')},
            },
        ),
        migrations.CreateModel(
            name='PaperAuthorship',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=10)),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='academic.faculty')),
                ('paper', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='authorships', to='academic.paper')),
            ],
            options={
                'unique_together': {('paper', 'faculty')},
            },
        ),
        migrations.AlterUniqueTogether(
            name='department',
            unique_together={('school', 'name')},
        ),
    ]
