# Generated by Django 5.2.7 on 2026-05-08 04:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='institutional_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='institutional_email_verified',
            field=models.BooleanField(default=False),
        ),
    ]
