# Generated by Django 5.2.7 on 2026-05-08 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_add_institutional_email_verification'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='status',
            field=models.CharField(choices=[('draft', 'Draft'), ('published', 'Published'), ('in-review', 'In Review')], default='published', max_length=20),
        ),
    ]
