# Generated by Django 5.2.7 on 2026-03-11 19:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0002_facultysuggestiondecision'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='journals',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='low_category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='low_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mid_category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='mid_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='source_profile',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='faculty',
            name='themes',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='top_category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='top_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='engagement_metrics',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='faculty_affiliations',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='faculty_members',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='low_category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='low_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='mid_category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='mid_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='source_metadata',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='source_record',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AddField(
            model_name='paper',
            name='top_category_urls',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='top_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
