# Generated by Django 5.2.7 on 2026-05-08 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_add_paper_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='faculty',
            name='personal_website',
            field=models.URLField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='faculty',
            name='qualifications',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='faculty',
            name='research_interests',
            field=models.TextField(blank=True, null=True),
        ),
    ]
