# Generated by Django 5.2.7 on 2026-03-11 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0003_faculty_category_urls_faculty_journals_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='embedding_model',
            field=models.CharField(blank=True, default='', max_length=64),
        ),
        migrations.AddField(
            model_name='paper',
            name='embedding_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='paper',
            name='paper_embedding',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
