# Generated by Codex on 2026-04-22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0004_paper_embedding_model_paper_embedding_updated_at_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="faculty",
            name="school",
            field=models.CharField(blank=True, max_length=150, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="school_affiliations",
            field=models.JSONField(blank=True, default=list),
        ),
    ]
