# Generated by Django 5.2.7 on 2026-05-09 21:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0004_add_faculty_profile_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='paper',
            name='mid_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AddField(
            model_name='paper',
            name='top_level_categories',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
