# Generated by Codex on 2026-04-22

from django.db import migrations, models
import django.db.models.deletion


STANDARD_SCHOOLS = [
    ("College of Health and Human Services", "CHHS"),
    ("Fulton School of Liberal Arts", "FSLA"),
    ("Henson School of Science & Technology", "HSST"),
    ("Perdue School of Business", "PSB"),
    ("Seidel School of Education", "SSE"),
    ("Clarke Honors College", "CHC"),
]

MAX_LABEL_LENGTH = 255


SCHOOL_ALIASES = {
    "college of health and human services": "College of Health and Human Services",
    "school of health sciences": "College of Health and Human Services",
    "school of social work": "College of Health and Human Services",
    "fulton school of liberal arts": "Fulton School of Liberal Arts",
    "school of liberal arts": "Fulton School of Liberal Arts",
    "henson school of science & technology": "Henson School of Science & Technology",
    "henson school of science and technology": "Henson School of Science & Technology",
    "school of science and technology": "Henson School of Science & Technology",
    "school of science & technology": "Henson School of Science & Technology",
    "school of technology": "Henson School of Science & Technology",
    "perdue school of business": "Perdue School of Business",
    "franklin p. perdue school of business": "Perdue School of Business",
    "franklin perdue school of business": "Perdue School of Business",
    "seidel school of education": "Seidel School of Education",
    "school of education": "Seidel School of Education",
    "clarke honors college": "Clarke Honors College",
}


def normalize(value):
    return " ".join(str(value or "").strip().lower().replace("&", "and").split())


def to_list(value):
    if isinstance(value, list):
        return [str(item).strip() for item in value if str(item).strip()]
    if isinstance(value, str):
        return [part.strip() for part in value.split(",") if part.strip()]
    return []


def unique(items):
    seen = set()
    result = []
    for item in items:
        item = str(item or "").strip()
        if not item:
            continue
        key = normalize(item)
        if key in seen:
            continue
        seen.add(key)
        result.append(item)
    return result


def db_label(value):
    label = str(value or "").strip()
    if not label or len(label) > MAX_LABEL_LENGTH:
        return ""
    return label


def canonical_school(value):
    key = normalize(value)
    if key in SCHOOL_ALIASES:
        return SCHOOL_ALIASES[key]
    for name, _code in STANDARD_SCHOOLS:
        if normalize(name) == key:
            return name
    return ""


def seed_and_backfill(apps, schema_editor):
    School = apps.get_model("academic", "School")
    Department = apps.get_model("academic", "Department")
    Faculty = apps.get_model("academic", "Faculty")

    schools_by_name = {}
    for order, (name, code) in enumerate(STANDARD_SCHOOLS, start=1):
        school, _created = School.objects.get_or_create(
            name=name,
            defaults={"code": code, "display_order": order, "is_active": True},
        )
        changed = False
        if not school.code:
            school.code = code
            changed = True
        if school.display_order != order:
            school.display_order = order
            changed = True
        if changed:
            school.save(update_fields=["code", "display_order", "updated_at"])
        schools_by_name[name] = school

    school_names = {normalize(name) for name, _code in STANDARD_SCHOOLS}

    for faculty in Faculty.objects.all():
        school_candidates = unique(
            [faculty.school]
            + to_list(getattr(faculty, "school_affiliations", []))
            + [faculty.department]
            + to_list(getattr(faculty, "department_affiliations", []))
        )
        canonical_schools = unique(
            [canonical_school(candidate) for candidate in school_candidates]
        )
        school_objects = [
            schools_by_name[name] for name in canonical_schools if name in schools_by_name
        ]

        department_candidates = unique(
            [faculty.department] + to_list(getattr(faculty, "department_affiliations", []))
        )
        department_names = [
            db_label(name)
            for name in department_candidates
            if normalize(name) not in school_names and not canonical_school(name)
        ]
        department_names = [name for name in department_names if name]

        primary_school = school_objects[0] if school_objects else None
        department_objects = []
        for department_name in department_names:
            department, _created = Department.objects.get_or_create(
                school=primary_school,
                name=department_name,
                defaults={"is_active": True},
            )
            department_objects.append(department)

        primary_department = department_objects[0] if department_objects else None

        if primary_school:
            faculty.primary_school = primary_school
        if primary_department:
            faculty.primary_department = primary_department

        salisbury_email = bool(
            faculty.email
            and str(faculty.email).lower().endswith(
                ("@salisbury.edu", "@gulls.salisbury.edu")
            )
        )
        has_su_evidence = bool(
            faculty.user_id
            or salisbury_email
            or primary_school
            or primary_department
            or faculty.is_approved
        )

        if has_su_evidence:
            faculty.confirmed_su_faculty = True
            faculty.review_status = "confirmed_su"
            faculty.is_approved = True
            faculty.profile_visibility = True
        else:
            faculty.confirmed_su_faculty = False
            faculty.review_status = "external"
            faculty.is_approved = False
            faculty.profile_visibility = False

        faculty.save(
            update_fields=[
                "primary_school",
                "primary_department",
                "confirmed_su_faculty",
                "review_status",
                "is_approved",
                "profile_visibility",
                "updated_at",
            ]
        )
        if school_objects:
            faculty.schools.add(*school_objects)
        if department_objects:
            faculty.departments.add(*department_objects)


def reverse_seed(apps, schema_editor):
    Faculty = apps.get_model("academic", "Faculty")
    Faculty.objects.update(confirmed_su_faculty=False, review_status="pending")


class Migration(migrations.Migration):

    dependencies = [
        ("academic", "0005_faculty_school_fields"),
    ]

    operations = [
        migrations.CreateModel(
            name="School",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255, unique=True)),
                ("code", models.CharField(blank=True, max_length=32, null=True, unique=True)),
                ("is_active", models.BooleanField(default=True)),
                ("display_order", models.PositiveIntegerField(default=0)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
            options={"ordering": ["display_order", "name"]},
        ),
        migrations.CreateModel(
            name="Department",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=255)),
                ("code", models.CharField(blank=True, max_length=32, null=True)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "school",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="departments",
                        to="academic.school",
                    ),
                ),
            ],
            options={
                "ordering": ["school__display_order", "school__name", "name"],
                "unique_together": {("school", "name")},
            },
        ),
        migrations.AddField(
            model_name="faculty",
            name="cleanup_notes",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="faculty",
            name="confirmed_su_faculty",
            field=models.BooleanField(db_index=True, default=False),
        ),
        migrations.AddField(
            model_name="faculty",
            name="review_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending Review"),
                    ("confirmed_su", "Confirmed SU Faculty"),
                    ("external", "External Collaborator"),
                    ("archived", "Archived"),
                    ("rejected", "Rejected"),
                ],
                db_index=True,
                default="pending",
                max_length=24,
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="primary_department",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_faculty",
                to="academic.department",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="primary_school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="primary_faculty",
                to="academic.school",
            ),
        ),
        migrations.AddField(
            model_name="faculty",
            name="departments",
            field=models.ManyToManyField(blank=True, related_name="faculty", to="academic.department"),
        ),
        migrations.AddField(
            model_name="faculty",
            name="schools",
            field=models.ManyToManyField(blank=True, related_name="faculty", to="academic.school"),
        ),
        migrations.RunPython(seed_and_backfill, reverse_seed),
    ]
