# Generated by Django 5.2.7 on 2026-05-11 02:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0005_add_taxonomy_category_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='CollaborationInquiry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('target_faculty_name', models.CharField(max_length=255)),
                ('target_faculty_id', models.CharField(blank=True, max_length=64)),
                ('target_department', models.CharField(blank=True, max_length=255)),
                ('target_school', models.CharField(blank=True, max_length=255)),
                ('shared_keywords', models.JSONField(blank=True, default=list)),
                ('note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('reviewed', 'Reviewed'), ('closed', 'Closed')], default='pending', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('from_faculty', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaboration_inquiries', to='academic.faculty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
