# Generated by Django 5.2.7 on 2026-05-11 03:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0006_collaboration_inquiry'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationinquiry',
            name='requester_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='requester_name',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='requester_organization',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='source_type',
            field=models.CharField(choices=[('faculty', 'Faculty (internal)'), ('external', 'External stakeholder')], default='faculty', max_length=16),
        ),
        migrations.AlterField(
            model_name='collaborationinquiry',
            name='from_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='sent_collaboration_inquiries', to='academic.faculty'),
        ),
    ]
