# Generated by Django 5.2.7 on 2026-05-11 20:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_inquiry_source_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationinquiry',
            name='reviewed_by',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
