# Generated by Django 5.2.7 on 2026-04-23 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0007_contactpagesettings_contactteammember'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='contactteammember',
            name='photo_url',
        ),
        migrations.AddField(
            model_name='contactteammember',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='contact_photos/'),
        ),
    ]
