# Generated by Django 5.2.7 on 2026-05-11 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_add_reviewed_by_to_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='AdminAuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('admin_username', models.CharField(max_length=150)),
                ('admin_display_name', models.CharField(blank=True, max_length=255)),
                ('action', models.CharField(choices=[('approve_faculty', 'Approved Faculty'), ('reject_faculty', 'Rejected Faculty'), ('bulk_approve', 'Bulk Approved Faculty'), ('bulk_reject', 'Bulk Rejected Faculty'), ('toggle_visibility', 'Toggled Profile Visibility'), ('delete_faculty', 'Deleted Faculty'), ('update_inquiry', 'Updated Inquiry')], max_length=32)),
                ('target_type', models.CharField(blank=True, max_length=32)),
                ('target_id', models.IntegerField(blank=True, null=True)),
                ('target_name', models.CharField(blank=True, max_length=255)),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
