# Generated by Django 5.2.7 on 2026-04-23 18:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0008_remove_contactteammember_photo_url_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='faculty',
            name='categories',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='category_urls',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='low_category_urls',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='low_level_categories',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mid_category_urls',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='mid_level_categories',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='source_profile',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='top_category_urls',
        ),
        migrations.RemoveField(
            model_name='faculty',
            name='top_level_categories',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='category_urls',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='low_category_urls',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='low_level_categories',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='mid_category_urls',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='mid_level_categories',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='source_metadata',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='source_record',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='top_category_urls',
        ),
        migrations.RemoveField(
            model_name='paper',
            name='top_level_categories',
        ),
    ]
