# Generated by Django 5.2.7 on 2026-05-16 04:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0010_project_collaboration_inquiries'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='collaborationinquiry',
            name='message_subject',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='recipient_faculty',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='received_admin_messages', to='academic.faculty'),
        ),
        migrations.AddField(
            model_name='collaborationinquiry',
            name='sender_admin',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sent_admin_messages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='collaborationinquiry',
            name='source_type',
            field=models.CharField(choices=[('faculty', 'Faculty (internal)'), ('external', 'External stakeholder'), ('admin', 'Admin message')], default='faculty', max_length=16),
        ),
    ]
