# Generated by Django 5.2.7 on 2026-05-16 11:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0011_add_admin_message_fields_to_inquiry'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportTicket',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_type', models.CharField(choices=[('bug', 'Bug Report'), ('account', 'Account Issue'), ('content', 'Content / Data Issue'), ('feature', 'Feature Request'), ('other', 'Other')], default='other', max_length=32)),
                ('subject', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('in_progress', 'In Progress'), ('resolved', 'Resolved'), ('closed', 'Closed')], db_index=True, default='open', max_length=16)),
                ('admin_notes', models.TextField(blank=True)),
                ('resolved_by', models.CharField(blank=True, max_length=150)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('faculty', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='support_tickets', to='academic.faculty')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
