# Generated by Django 5.2.7 on 2026-05-16 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0012_add_support_ticket'),
    ]

    operations = [
        migrations.AddField(
            model_name='supportticket',
            name='submitter_email',
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AddField(
            model_name='supportticket',
            name='submitter_name',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
