# Generated by Django 5.2.7 on 2026-05-20 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academic', '0015_add_faculty_portal_message'),
    ]

    operations = [
        migrations.AddField(
            model_name='contactpagesettings',
            name='api_documentation_url',
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name='contactpagesettings',
            name='documentation_url',
            field=models.URLField(blank=True),
        ),
    ]
